export declare function castToBigint(obj: any, name_for_err: string): bigint | undefined;
export declare function castToBigintNotUndef(obj: any, name_for_err: string): bigint;
export declare function checkBigintMin(obj: bigint, name_for_err: string, min: bigint): bigint;
export declare function checkBigintMax(obj: bigint, name_for_err: string, max: bigint): bigint;
export declare function castToString(obj: any, name_for_err: string): string | undefined;
export declare function castToStringNotUndef(obj: any, name_for_err: string): string;
export declare function checkStringMinLength(obj: string, name_for_err: string, min_length: number): string;
export declare function checkStringMaxLength(obj: string, name_for_err: string, max_length: number): string;
export declare function castToObject<Type>(obj: any, name_for_err: string): Type | undefined;
export declare function castToObjectNotUndef<Type>(obj: any, name_for_err: string): Type;
export declare function castToBigintArray(obj: any, name_for_err: string): bigint[] | undefined;
export declare function castToBigintOrStringArray(obj: any, name_for_err: string): bigint[] | string[] | undefined;
